### ISSUE TITLE
adapter file for trimming input

### ISSUE THREAD

**Issue by swlong** [jonathanjacobs/CLC-Genomics#1]
The included adapter file is for ONT 1D in the Illumina package... can we get adapter files for NexteraXT? 

I tried to find online, found instructions on CLC website but seemed to link to a document that's gone.

**Comment by jonathanjacobs** [comment]
Sorry to have just now seen this Wes - apparently my Git notifications were disabled. :( 

The trimming algo in the CLC workflows includes an automatic adapter trimming tool that find common adapters and removes them. This can be disabled if you don't want to do it - but with it enabled it removes the need for separate adapter sequence lists in nearly all cases (with Illumina PE data at least). Details on the trimming tool's adapter detection algo can be found here:
 https://resources.qiagenbioinformatics.com/manuals/clcgenomicsworkbench/current/index.php?manual=Adapter_trimming.html

An example of what this looks like in the QC/Trimming report is attached as a PDF (see page 4)

[173-008-2_S8_L001_R1_001 (paired, trim report).pdf](https://github.com/jonathanjacobs/CLC-Genomics/files/5003548/173-008-2_S8_L001_R1_001.paired.trim.report.pdf)

As for how to build a NexteraXT specific adapter sequence - Q can't distribute those (legally) - but you can build them yourself pretty easily. If you need me to send one to you personally - let me know.
